version: "3.2"
services:
  streaming:
    image: orcasound/orcanode:arm32v7
    build: ./
    command: ./stream.sh
    restart: always
    env_file: .env
    ports:
      - "1234:1234"
      - "8080:8080"
      - "6379:6379"
    devices:
      - "/dev/snd:/dev/snd"
    privileged: true

  logspout:
    # Use unofficial logspout that's been compiled for armhf
    # TODO: Build an updated version of this image. Looks unmaintained.
    image: emdem/raspi-logspout
    command: ${SYSLOG_URL}
    restart: always
    hostname: ${NODE_NAME}
    env_file: .env
    environment:
      - SYSLOG_HOSTNAME=${NODE_NAME}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8000:8000"
  redis:
    #
    # TODO bind to local port only
    image: redis:latest
    command: redis-server --appendonly yes
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    
